Add Automation script to shard a pbf using AWS
osmlab/atlas-generator pull request #166
Opened 2020-10-16 15:56 UTC by atiannicelli

### Description:

Add scripts and README to shard a pbf URL using AWS EC2 in preparation to generate atlas files. The README aded gives detailed descriptions of the scripts and how to use them.

### Potential Impact:

This will not impact any atlas-generation code. The scrip is meant to accompany the atlas-generator to provide AWS automaton support.

### Unit Test Approach:

No unit tests were added for this script. 

### Test Results:

I have tested this script by executing it against our AWS configuration. I successfully sharded 2 different planet files (this took ~4 hours each). I have also executed this script on a number of smaller pbf URLs and verified that the output of these runs were the same as manually produced sharding runs.

------

In doubt: [Contributing Guidelines](https://github.com/osmlab/atlas/blob/dev/CONTRIBUTING.md)

2020-10-19 21:35 UTC, zlavergne requested changes
Just a few minor things but overall it looks good. I can give it a more thorough pass if needed

2020-10-19 21:35 UTC, zlavergne commented on scripts/cloudPBFShardControl/cloudPBFShardControl.py
> +def parse_args(cloudctl):
```suggestion
def parse_args(cloudctl: CloudPBFShardControl):
```

2020-10-19 21:35 UTC, zlavergne commented on scripts/cloudPBFShardControl/cloudPBFShardControl.py
> +    parser_prep.set_defaults(func=CloudPBFShardControl.prep)
```suggestion
    parser_prep.set_defaults(func= cloudctl.prep)
```

2020-10-19 21:35 UTC, zlavergne commented on scripts/cloudPBFShardControl/cloudPBFShardControl.py
> +    parser_shard.set_defaults(func=CloudPBFShardControl.shard)
```suggestion
    parser_shard.set_defaults(func= cloudctl.shard)
```

2020-10-19 21:35 UTC, zlavergne commented on scripts/cloudPBFShardControl/cloudPBFShardControl.py
> +    parser_sync.set_defaults(func=CloudPBFShardControl.sync)
```suggestion
    parser_sync.set_defaults(func= cloudctl.sync)
```

2020-10-19 21:35 UTC, zlavergne commented on scripts/cloudPBFShardControl/cloudPBFShardControl.py
> +    parser_clean.set_defaults(func=CloudPBFShardControl.clean)
```suggestion
    parser_clean.set_defaults(func= cloudctl.clean)
```

2020-10-19 21:35 UTC, zlavergne commented on scripts/cloudPBFShardControl/cloudPBFShardControl.py
> +        # self.put_files([awsConfig, awsCredentials], remoteDir)
is this still useful? maybe remove if not

2020-10-21 18:24 UTC, zlavergne commented on scripts/cloudPBFShardControl/cloudPBFShardControl.py
> +        finish()
I thought I had put a comment on this in here but I didn't see it...

Something to consider with these checks

2020-10-21 18:32 UTC, zlavergne commented on scripts/cloudPBFShardControl/pbfShardGenerator.py
> +    if args.version:
Same convo as above about the conditional checks

2020-10-29 02:02 UTC, matthieun reviewed
This sounds like a great idea! Maybe @lucaspcram can take a look at the python code?

Just one nit, the sharding tree which is checked in... Is it for testing? If yes maybe a smaller one could do? Otherwise we'd rather have the user provide it, so we do not have to check it in. We have checked in large files in the past and regret it ever since!

2020-10-29 13:09 UTC, atiannicelli commented
thanks @matthieun , good comment. I will refactor a bit to fetch the sharding tree file from S3 like the other scripts do and remove the sharding tree file from this commit.

2020-10-29 19:26 UTC, lucaspcram approved these changes
The python looks good to me!

2020-10-29 21:30 UTC, jwpgage approved these changes
Thanks for these scripts @atiannicelli!

2020-11-02 21:41 UTC, matthieun approved these changes
Nice!

2020-11-02 21:41 UTC, merged